### ISSUE TITLE
"Zoom out" animation feels a bit odd

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-flame-graph#1]
Can't quite put it into words, but here's a GIF based on the website:

![gif](https://dzwonsemrish7.cloudfront.net/items/2Y340o470A1g2C2z3T1E/Screen%20Recording%202018-07-14%20at%2008.31%20pm.gif?v=cbdd39f3)

And here are the frames:

<img width="987" alt="screen shot 2018-07-14 at 20 32 23" src="https://user-images.githubusercontent.com/810438/42727809-316213ba-87a5-11e8-8910-a9b6b4c1314a.png">
<img width="987" alt="screen shot 2018-07-14 at 20 32 29" src="https://user-images.githubusercontent.com/810438/42727810-317d54cc-87a5-11e8-82ed-dd9c90058f16.png">
<img width="987" alt="screen shot 2018-07-14 at 20 32 35" src="https://user-images.githubusercontent.com/810438/42727811-3197b1fa-87a5-11e8-96f9-9902fe52570b.png">
<img width="990" alt="screen shot 2018-07-14 at 20 32 40" src="https://user-images.githubusercontent.com/810438/42727812-31b16e6a-87a5-11e8-9ecd-f1af27563662.png">
<img width="992" alt="screen shot 2018-07-14 at 20 32 45" src="https://user-images.githubusercontent.com/810438/42727813-31cb3016-87a5-11e8-8e55-546be55a5026.png">

Could there be a z-order issue?

**Comment by gaearon** [comment]
Maybe it could animate the opacity much faster than the width? Then we wouldn't get to see those text overlays.

**Comment by bvaughn** [comment]
I agree that the current animation feels a bit odd.

I think the actual problem is that new nodes "pop" in but existing nodes animate. I wish there was an easy way to fade in new nodes.

**Comment by bvaughn** [comment]
Oooh! I have an idea for this.

**Comment by gaearon** [comment]
Perhaps the new nodes should start their positions off screen, with a horizontally proportional scale?

And as we "zoom in", they would slide from left and right, their widths decreasing until they all fit in the screen.

````
               |********** viewport ***********|
[  a    ][ b  ][           current             ][     c     ]
    [  a ][ b  ][         current            ][   c   ]
      [   a ][ b  ][         current      ][   c    ]
               [ a ][b][     current   ][ c   ]
```

**Comment by bvaughn** [comment]
Hm 🤔I could do that, but then I'd have to pay the cost of rendering them all even if they weren't visible.

**Comment by gaearon** [comment]
I only mean you'd show them right before the animation starts. You'd have to show them regardless a second later — with lesser widths of course. Maybe you can immediately skip the ones that will "end up" small enough in the final state.

**Comment by bvaughn** [comment]
Maybe I could do this with a CSS animation that animates the translate property...

**Comment by bvaughn** [comment]
It's possible. I've tried a couple fo things though and they all feel a bit heavy handed.

For example, I can't always animate from outside in– because scrolling vertically would be weird. (Things should already be in place in that case, unlike the clicking to zoom in or out case.)

So I'd have to add derived state to an ancestor to pass down a prop so that `ChartNode`s know when to appear in place and when to slide in from the side. But in order to do a side slide in, I'd have to also convert `ChartNode` to a class component so I can do an effect on-mount.

Not sure it's a good trade off.

**Comment by gaearon** [comment]
Maybe not — you know this code much better than I do :-)

But the current animation feels broken. Maybe as an alternative the width animation could be deferred after a very quick opacity animation? Then at least we wouldn't see that odd overlapping.

**Comment by bvaughn** [comment]
The current animation doesn't feel that broken to me 😄 I understand where you're coming from, but it's a fast animation and overall things feel snappy enough that the occasional overlap when zooming out doesn't bother me.

I did experiment with delaying the fade-in until after the width had completed. This requires a bit of additional derived state to work (for the same reasons mentioned prior) but it is doable. It made things feel a bit more sluggish overall though. (Subjectively.)

The quickest fix would be to just remove [this line](https://github.com/bvaughn/react-flame-graph/blob/b2ee27a0252938ea430117d653507f2d19ad6303/src/ItemRenderer.js#L45-L51) but that would negatively impact performance too.

As a side note, I tried replacing the SVG elements with divs since they're flatter, and the transitions can be GPU accelerated– to possibly offset any negative performance impacts of making the animations more complex– but there seems to be a goofy transition bug that I haven't been able to nail down. Maybe related to the GPU acceleration, not sure. The transitioning divs sometimes flicker/flash opacity.

**Comment by bvaughn** [comment]
Ultimately, I've tried a few things and I was unable to find an animation that looked better, felt as fast, and didn't add a lot of overhead (e.g. converting function components to class components, adding derived state).

I'm going to mark this as "help wanted" in case anyone else wants to take a stab at it– but I don't think I'm going to. 😄

**Comment by wuweiweiwu** [comment]
I’d love to pick this up! 😀

**Comment by sompylasar** [comment]
I thought I'd share my experience with a similar component: an archive timeline. It was initially built with divs and DOM style standard jQuery transitions (circa 2011) which were like a polyfill for the modern CSS transitions and animations. These animations, including zoom, were terrible because they were not synchronized with each other and with the user input.

Later, because of a different problem on a larger number of divs – performance (even though they were windowed, adding and removing nodes wasn't fast back then), I've rewritten the component entirely (vanilla JS, no React) with performance and user-input-driven animations in mind: timestamp-based data model optimized for range reads; `canvas`-based immediate mode rendering with `requestAnimationFrame` update loop starting at user interactions and trailing up to idle. There are still a few DOM nodes used for cursors, tooltips, selection ranges, but the user input is tracked uniformly on the timeline as a whole, pointer event coordinates are mapped to timestamps, and the only thing they drive is the visible timestamp range; everything else is derived on each frame.

Here's a screen recording of this `canvas`-based component in action (zoom is controlled with `mousewheel`):
![](https://user-images.githubusercontent.com/498274/42740026-0f832e30-8856-11e8-9cd9-1b882c9d2998.gif)

Notice how the timeline immediately reacts to the change in user input. The timeline is always animating to the target visible range (until it's idle).

The gist of the above is: CSS approach of describing transitions and animations is flawed for such user-driven state.

Feel free to poke me with any follow-up questions. Thank you for attention.

**Comment by vincentriemer** [comment]
Would you consider this any better?

![neglectedfreeichidna-max-14mb](https://user-images.githubusercontent.com/1398555/42740276-116707d6-8873-11e8-89be-939f442c1fbe.gif)

**Comment by vincentriemer** [comment]
Tweaked the animation curve to a pure deceleration curve which I think works better for an animation this short:

![](https://thumbs.gfycat.com/BlindBadBobwhite-size_restricted.gif)

[60fps version of the gif](https://gfycat.com/BlindBadBobwhite)

**Comment by gaearon** [comment]
Love this. Thank you!

**Comment by bvaughn** [comment]
Hey @sompylasar :wave: Thanks for sharing your experiences. The demo component you recorded looks slick :smile:

Hey @vincentriemer :smile: Thanks for lending a hand!

Looking at PR #2, I wouldn't expect to see much of a difference except for a slight difference in opacity during a "zoom out". Here are the interactions slowed down to 10% speed:

## master
![master](https://user-images.githubusercontent.com/29597/42765809-b0ff1324-88cd-11e8-8542-00fcb203810b.gif)

## PR 2
![pr-2](https://user-images.githubusercontent.com/29597/42765818-b4c26cfe-88cd-11e8-9b29-43546f2a242a.gif)

If you think of the above interactions as 4 sequences, I think PR #2 only impacts the fourth. Is that correct?

I think the interact Dan had the most problems with was the second one (where new nodes pop in on top of animating nodes) but maybe I misunderstood.

**Comment by vincentriemer** [comment]
Dan can correct me if I'm wrong, but I was under the impression the largest issue was this overlapping of text, which my PR fixes:

![screen shot 2018-07-16 at 11 01 04 am](https://user-images.githubusercontent.com/1398555/42766159-b5031ce4-88e7-11e8-93dc-58135e2dab75.png)

**Comment by bvaughn** [comment]
The text overlap is subtle. The one that nags me (a little, although not enough to sacrifice performance) is the green nodes popping in on top of the animating/fading yellow ones:

![screen shot 2018-07-16 at 8 04 26 am](https://user-images.githubusercontent.com/29597/42766287-e1b7a048-88ce-11e8-9dba-2bf8578b5f46.png)

**Comment by gaearon** [comment]
I think text overlap was the biggest issue for me because it creates "fake boldness" in those spots and draws attention to the artifacts. I find them easier to miss when there's no overlap.

**Comment by bvaughn** [comment]
Interesting! 😄 I still don't see that as much of a problem.

But we could fix that in a different way that doesn't add an additional `<rect>` node– by replacing the `opacity` conditional with a lighter color variant.

**Comment by gaearon** [comment]
On iOS using solid fill color is always faster than opacity composition. Don't know about browsers though.

**Comment by bvaughn** [comment]
:grin: Maybe [bvaughn/react-flame-graph/pull/3](https://github.com/bvaughn/react-flame-graph/pull/3)?

![resize](https://user-images.githubusercontent.com/29597/42774277-28f1c6c0-88e6-11e8-93d2-478f88f03aa1.gif)
